### ISSUE TITLE
traefik dashboard changes

### ISSUE THREAD

**Issue by khassel** [realtarget/traefik2-docker-stack#1]
Hi,

since traefik release [v2.0.0-rc3](https://github.com/containous/traefik/releases/tag/v2.0.0-rc3) your dashboard setup is broken.

Replacing
````
- "traefik.http.services.traefik.loadbalancer.server.port=8080"
````
with
````
- "traefik.http.routers.traefik.service=api@internal"
````
works.

**Comment by realtarget** [comment]
Thanks for the info. Fixed + tested with traefik [v2.0.0-rc4](https://github.com/containous/traefik/releases/tag/v2.0.0-rc4).
