### ISSUE TITLE
Issue with initial configuration

### ISSUE THREAD

**Issue by caseydierking** [realtarget/traefik2-docker-stack#2]
Hey there! Really excited to have found this repo. I think it helps simplify an initial install of Traefik v2 with some various services. 

I'm trying to just get it up and running and I ran into an issue with the certificate not validating. It appears as if the certificate is granted to TRAEFIK DEFAULT CERT instead of using lets encrypt.
Err. Cert_Authority_Invalid

I was wondering if you had any thoughts on this. I followed the instructions to modify the docker-compose with my email and correct domain. Along with creating the acme.json file.

**Comment by realtarget** [comment]
Can you please post your traefik.toml and docker-compose.yml?

**Comment by caseydierking** [comment]
Thanks for the response, I'll get this to you this weekend.
